some fixes

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -375,35 +375,35 @@ jobs:
       - install_nodejs
       
       
-    - run:
-        name: Backend smoke test.
-        command: |
-            BACKEND_IP=$(aws ec2 describe-instances \
-          --query 'Reservations[*].Instances[*].PublicIpAddress' \
-          --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
-          --output text )
-          export API_URL=http://${BACKEND_IP}:3030
-          if curl -s $API_URL/api/status | grep "ok"
-          then 
-            exit 0
-          else 
-            exit 1
-          fi 
-    - run:
-        name: Frontend smoke test.
-        command: |
-          URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com"
-          if curl -s ${URL} | grep "Welcome"
-          then
-            return 1
-          else
-            return 2
-          fi
-    # Here's where you will add some code to rollback on failure
-    - destroy-environment:
-        workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
-    - revert-migrations:
-        workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
+      - run:
+          name: Backend smoke test.
+          command: |
+              BACKEND_IP=$(aws ec2 describe-instances \
+            --query 'Reservations[*].Instances[*].PublicIpAddress' \
+            --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
+            --output text )
+            export API_URL=http://${BACKEND_IP}:3030
+            if curl -s $API_URL/api/status | grep "ok"
+            then 
+              exit 0
+            else 
+              exit 1
+            fi 
+      - run:
+          name: Frontend smoke test.
+          command: |
+            URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com"
+            if curl -s ${URL} | grep "Welcome"
+            then
+              return 1
+            else
+              return 2
+            fi
+      # Here's where you will add some code to rollback on failure
+      - destroy-environment:
+          workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
+      - revert-migrations:
+          workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
 
   cloudfront-update:
     docker:
